<html>
<head>
<META http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>
     CIP Visual Basic.NET documentation for interface "IpfcAngleDimensionSense"
    </title>
<link href="cipdoc_default.css" type="text/css" rel="stylesheet">
<script language="JAVASCRIPT">
  function findProperNode ()
  {  
   
     top.frames [0].document.apiwizard.api (
      3,
      4
     ); 
    
  } 
 </script>
</head>
<body onLoad="findProperNode()" class="frame-entity">
<table cellspacing="0" width="100%" border="0" class="toolbar">
<tr>
<td class="toolbar-navigation"><a href="library.html">Library</a>&nbsp;|&nbsp;<a href="m-pfcDimension2D.html">Module</a></td><td class="toolbar-frame-links"><a target="_top" href="index.html">Frames</a>&nbsp;|&nbsp;<a target="_top" href="t-pfcDimension2D-AngleDimensionSense.html">Expand</a></td><td class="toolbar-lib-name">
  
 </td>
</tr>
</table>
<hr>
<h2>Interface&nbsp;IpfcAngleDimensionSense</h2>
<hr>
<br>
<tt><b>DEPRECATED: </b>
  since Creo 4
  <br>
</tt><tt><b>SUCCESSOR(S): </b><a class="method" href="t-pfcDimension-AngularDimSense.html">AngularDimSense</a>
<p></p>
</tt><b>Description</b>
<br>
<br>This interface is a dimension sense type referring to the angle between two straight entities. 
<br>
<br>The dimension sense gives more information about how the dimension attaches to the entity, 
for example, to what part of the entity, and in what direction the dimension runs. 
<br>
<dl>
<dt>
<b>See Also:</b>
</dt>
<dd>
<tt><b><tt><b><a class="enumtype" href="t-pfcDimension2D-DrawingDimCreateInstructions.html">IpfcDrawingDimCreateInstructions</a></b></tt></b></tt>, <tt><b><a class="method" href="t-pfcDimension2D-Dimension2D.html#GetDimensionSenses">IpfcDimension2D.GetDimensionSenses()</a></b></tt>
</dd>
</dl>
<dl>
<dt>
<b>Direct Parent Classes:</b>
</dt>
<dd>
<a class="class" href="t-pfcDimension2D-DimensionSense.html">IpfcDimensionSense</a>
</dd>
</dl>
<br>
<hr>
<br>
<b>Property Summary</b>
<br>
<br>
<table cellpadding="3" border="0" class="method-summary">
<tr>
<td></td>
</tr>
<tr>
<td class="return-type"><tt>Property</tt></td><td class="func-signature"><tt><a class="method" href="#AngleOptions">AngleOptions</a></tt></td><td class="return-type"><tt>as <a class="type" href="t-pfcDimension2D-DimensionAngleOptions.html">IpfcDimensionAngleOptions</a> [optional]</tt></td>
</tr>
<tr>
<td></td>
<tr>
<td><tt><b>DEPRECATED: </b>
  since Creo 4
  </tt></td>
</tr>
<tr>
<td><tt><b>SUCCESSOR(S): </b>
         &lt;reference 1 to unknown entity pfcDimension::AngularDimSense::Options&gt;
    </tt></td>
</tr>
<td colspan="2" class="entities-text">The flags determining the location of the angle dimension.</td>
</tr>
<tr>
<td></td>
</tr>
</table>
<br>
<hr>
<br>
<b>Method Summary</b>
<br>
<br>
<table cellpadding="3" border="0" class="method-summary">
<tr>
<td></td>
</tr>
<tr>
<td class="return-type"><tt>Function</tt></td><td class="func-signature"><tt><a class="method" href="#Create">CCpfcAngleDimensionSense.Create</a>
 (AngleOptions as <a class="type" href="t-pfcDimension2D-DimensionAngleOptions.html">IpfcDimensionAngleOptions</a> [optional])
 as <a class="type" href="t-pfcDimension2D-AngleDimensionSense.html">IpfcAngleDimensionSense</a></tt></td>
</tr>
<tr>
<td></td>
<tr>
<td><tt><b>DEPRECATED: </b>
  since Creo 4
  </tt></td>
</tr>
<tr>
<td><tt><b>SUCCESSOR(S): </b><a class="method" href="t-pfcDimension-AngularDimSense.html#Create">AngularDimSense.Create</a></tt></td>
</tr>
<td colspan="2" class="entities-text">Creates a new angle dimension sense object for use in creating a drawing dimension.
</td>
</tr>
<tr>
<td></td>
</tr>
</table>
<br>
<hr>
<br>
<b>Property Detail</b>
<br>
<hr>
<br>
<a name="AngleOptions">
<table cellpadding="5" cellspacing="0" border="0" class="method-def">
<tr>
<td class="return-type"><tt>Property</tt></td><td class="func-name"><tt>AngleOptions</tt></td><td class="return-type"><tt>as <a class="type" href="t-pfcDimension2D-DimensionAngleOptions.html">IpfcDimensionAngleOptions</a> [optional]</tt></td>
</tr>
</table>
</a>
<table border="0" class="method-doc">
<tr>
<td></td>
<tr>
<td><tt><b>DEPRECATED: </b>
  since Creo 4
  </tt></td>
</tr>
<tr>
<td><tt><b>SUCCESSOR(S): </b>
         &lt;reference 1 to unknown entity pfcDimension::AngularDimSense::Options&gt;
    </tt></td>
</tr>
<td>
<br>The flags determining the location of the angle dimension.<br>
<br>
</td>
</tr>
</table>
<br>
<br>
<hr>
<br>
<b>Method Detail</b>
<br>
<hr>
<br>
<a name="Create">
<table cellpadding="5" cellspacing="0" border="0" class="method-def">
<tr>
<td class="return-type"><tt>Function</tt></td><td class="func-name"><tt>CCpfcAngleDimensionSense.Create</tt></td><td class="func-params"><tt>
 (AngleOptions as <a class="type" href="t-pfcDimension2D-DimensionAngleOptions.html">IpfcDimensionAngleOptions</a> [optional])
 as <a class="type" href="t-pfcDimension2D-AngleDimensionSense.html">IpfcAngleDimensionSense</a></tt></td>
</tr>
</table>
</a>
<table border="0" class="method-doc">
<tr>
<td></td>
<tr>
<td><tt><b>DEPRECATED: </b>
  since Creo 4
  </tt></td>
</tr>
<tr>
<td><tt><b>SUCCESSOR(S): </b><a class="method" href="t-pfcDimension-AngularDimSense.html#Create">AngularDimSense.Create</a></tt></td>
</tr>
<td>
<br>Creates a new angle dimension sense object for use in creating a drawing dimension.
<br>
<dl>
<dt>
<b>See Also:</b>
</dt>
<dd>
<tt><b><a class="method" href="t-pfcModel2D-Model2D.html#CreateDrawingDimension">IpfcModel2D.CreateDrawingDimension()</a></b></tt>
</dd>
</dl>
<dl>
<dt>
<b>Parameters:</b>
</dt>
<dd>
<dl>
<dt>
<tt><b>AngleOptions</b></tt>
</dt>
<dd>The angle option flags used for the dimension.</dd>
</dl>
</dd>
</dl>
<dl>
<dt>
<b>Returns:</b>
</dt>
<dd>The created angle dimension sense object.</dd>
</dl>
</td>
</tr>
</table>
<br>
</body>
</html>
