<html>
<head>
<META http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>
     CIP Visual Basic.NET documentation for interface "IpfcDetailEntityInstructions"
    </title>
<link href="cipdoc_default.css" type="text/css" rel="stylesheet">
<script language="JAVASCRIPT">
  function findProperNode ()
  {  
   
     top.frames [0].document.apiwizard.api (
      3,
      116
     ); 
    
  } 
 </script>
</head>
<body onLoad="findProperNode()" class="frame-entity">
<table cellspacing="0" width="100%" border="0" class="toolbar">
<tr>
<td class="toolbar-navigation"><a href="library.html">Library</a>&nbsp;|&nbsp;<a href="m-pfcDetail.html">Module</a></td><td class="toolbar-frame-links"><a target="_top" href="index.html">Frames</a>&nbsp;|&nbsp;<a target="_top" href="t-pfcDetail-DetailEntityInstructions.html">Expand</a></td><td class="toolbar-lib-name">
  
 </td>
</tr>
</table>
<hr>
<h2>Interface&nbsp;IpfcDetailEntityInstructions</h2>
<hr>
<br>
<b>Description</b>
<br>
<br>This interface contains information used to describe a detail entity item.
It may be used when creating detail entities (<tt><b><a class="method" href="t-pfcDetail-DetailItemOwner.html#CreateDetailItem">IpfcDetailItemOwner.CreateDetailItem()</a></b></tt> and <tt><b><a class="method" href="t-pfcDetail-DetailSymbolDefItem.html#CreateDetailItem">IpfcDetailSymbolDefItem.CreateDetailItem()</a></b></tt>), or accessing existing entities (<tt><b><a class="method" href="t-pfcDetail-DetailEntityItem.html#Modify">IpfcDetailEntityItem.Modify()</a></b></tt> and <tt><b><a class="method" href="t-pfcDetail-DetailEntityItem.html#GetInstructions">IpfcDetailEntityItem.GetInstructions()</a></b></tt>).
<br>
<dl>
<dt>
<b>See Also:</b>
</dt>
<dd>
<tt><b><a class="method" href="t-pfcGeometry-LineDescriptor.html#Create">IpfcLineDescriptor.Create()</a></b></tt>, <tt><b><a class="method" href="t-pfcGeometry-ArcDescriptor.html#Create">IpfcArcDescriptor.Create()</a></b></tt>, <tt><b><a class="method" href="t-pfcGeometry-ArrowDescriptor.html#Create">IpfcArrowDescriptor.Create()</a></b></tt>, <tt><b><a class="method" href="t-pfcGeometry-CircleDescriptor.html#Create">IpfcCircleDescriptor.Create()</a></b></tt>, <tt><b><a class="method" href="t-pfcGeometry-SplineDescriptor.html#Create">IpfcSplineDescriptor.Create()</a></b></tt>, <tt><b><a class="method" href="t-pfcGeometry-BSplineDescriptor.html#Create">IpfcBSplineDescriptor.Create()</a></b></tt>, <tt><b><a class="method" href="t-pfcGeometry-EllipseDescriptor.html#Create">IpfcEllipseDescriptor.Create()</a></b></tt>, <tt><b><a class="method" href="t-pfcGeometry-PolygonDescriptor.html#Create">IpfcPolygonDescriptor.Create()</a></b></tt>, <tt><b><a class="method" href="t-pfcGeometry-CompositeCurveDescriptor.html#Create">IpfcCompositeCurveDescriptor.Create()</a></b></tt>, <tt><b><a class="method" href="t-pfcModel2D-Model2D.html#List2DViews">IpfcModel2D.List2DViews()</a></b></tt>, <tt><b><a class="method" href="t-pfcSheet-SheetOwner.html#GetSheetBackgroundView">IpfcSheetOwner.GetSheetBackgroundView()</a></b></tt>
</dd>
</dl>
<dl>
<dt>
<b>Direct Parent Classes:</b>
</dt>
<dd>
<a class="class" href="t-pfcDetail-DetailCreateInstructions.html">IpfcDetailCreateInstructions</a>
</dd>
</dl>
<br>
<hr>
<br>
<b>Property Summary</b>
<br>
<br>
<table cellpadding="3" border="0" class="method-summary">
<tr>
<td></td>
</tr>
<tr>
<td class="return-type"><tt>Property</tt></td><td class="func-signature"><tt><a class="method" href="#Color">Color</a></tt></td><td class="return-type"><tt>as <a class="type" href="t-pfcBase-ColorRGB.html">IpfcColorRGB</a> [optional]</tt></td>
</tr>
<tr>
<td></td><td colspan="2" class="entities-text">The color of the detail item.  If <tt>null</tt>, the default drawing color is used.</td>
</tr>
<tr>
<td></td>
</tr>
<tr>
<td class="return-type"><tt>Property</tt></td><td class="func-signature"><tt><a class="method" href="#FontName">FontName</a></tt></td><td class="return-type"><tt>as String [optional]</tt></td>
</tr>
<tr>
<td></td><td colspan="2" class="entities-text">The name of the linestyle.  If <tt>null</tt>, the default linestyle is used.</td>
</tr>
<tr>
<td></td>
</tr>
<tr>
<td class="return-type"><tt>Property</tt></td><td class="func-signature"><tt><a class="method" href="#Geometry">Geometry</a></tt></td><td class="return-type"><tt>as <a class="type" href="t-pfcGeometry-CurveDescriptor.html">IpfcCurveDescriptor</a></tt></td>
</tr>
<tr>
<td></td><td colspan="2" class="entities-text">The geometry of the detail entity.</td>
</tr>
<tr>
<td></td>
</tr>
<tr>
<td class="return-type"><tt>Property</tt></td><td class="func-signature"><tt><a class="method" href="#IsConstruction">IsConstruction</a></tt></td><td class="return-type"><tt>as Boolean [optional]</tt></td>
</tr>
<tr>
<td></td><td colspan="2" class="entities-text">Whether or not the entity is construction.  If <tt>null</tt>, the entity is not a construction entity.</td>
</tr>
<tr>
<td></td>
</tr>
<tr>
<td class="return-type"><tt>Property</tt></td><td class="func-signature"><tt><a class="method" href="#View">View</a></tt></td><td class="return-type"><tt>as <a class="type" href="t-pfcView2D-View2D.html">IpfcView2D</a> [optional]</tt></td>
</tr>
<tr>
<td></td><td colspan="2" class="entities-text">The drawing view associated with the entity.  This can be a view of a drawing model, or a drawing sheet background view.</td>
</tr>
<tr>
<td></td>
</tr>
<tr>
<td class="return-type"><tt>Property</tt></td><td class="func-signature"><tt><a class="method" href="#Width">Width</a></tt></td><td class="return-type"><tt>as Double [optional]</tt></td>
</tr>
<tr>
<td></td><td colspan="2" class="entities-text">The width of the entity line.  If <tt>null</tt>, the default width is used.</td>
</tr>
<tr>
<td></td>
</tr>
</table>
<br>
<hr>
<br>
<b>Method Summary</b>
<br>
<br>
<table cellpadding="3" border="0" class="method-summary">
<tr>
<td></td>
</tr>
<tr>
<td class="return-type"><tt>Function</tt></td><td class="func-signature"><tt><a class="method" href="#Create">CCpfcDetailEntityInstructions.Create</a>
 (inGeometry as <a class="type" href="t-pfcGeometry-CurveDescriptor.html">IpfcCurveDescriptor</a>, inView as <a class="type" href="t-pfcView2D-View2D.html">IpfcView2D</a> [optional])
 as <a class="type" href="t-pfcDetail-DetailEntityInstructions.html">IpfcDetailEntityInstructions</a></tt></td>
</tr>
<tr>
<td></td><td colspan="2" class="entities-text">Creates an instructions object describing how to construct a detail entity, for use in the methods <tt><b><a class="method" href="t-pfcDetail-DetailItemOwner.html#CreateDetailItem">IpfcDetailItemOwner.CreateDetailItem()</a></b></tt>, <tt><b><a class="method" href="t-pfcDetail-DetailSymbolDefItem.html#CreateDetailItem">IpfcDetailSymbolDefItem.CreateDetailItem()</a></b></tt> and <tt><b><a class="method" href="t-pfcDetail-DetailEntityItem.html#Modify">IpfcDetailEntityItem.Modify()</a></b></tt>.
</td>
</tr>
<tr>
<td></td>
</tr>
</table>
<br>
<hr>
<br>
<b>Property Detail</b>
<br>
<hr>
<br>
<a name="Color">
<table cellpadding="5" cellspacing="0" border="0" class="method-def">
<tr>
<td class="return-type"><tt>Property</tt></td><td class="func-name"><tt>Color</tt></td><td class="return-type"><tt>as <a class="type" href="t-pfcBase-ColorRGB.html">IpfcColorRGB</a> [optional]</tt></td>
</tr>
</table>
</a>
<table border="0" class="method-doc">
<tr>
<td></td><td>
<br>The color of the detail item.  If <tt>null</tt>, the default drawing color is used.<br>
<br>
</td>
</tr>
</table>
<br>
<hr>
<br>
<a name="FontName">
<table cellpadding="5" cellspacing="0" border="0" class="method-def">
<tr>
<td class="return-type"><tt>Property</tt></td><td class="func-name"><tt>FontName</tt></td><td class="return-type"><tt>as String [optional]</tt></td>
</tr>
</table>
</a>
<table border="0" class="method-doc">
<tr>
<td></td><td>
<br>The name of the linestyle.  If <tt>null</tt>, the default linestyle is used.<br>
<br>
<p>
<b>Exceptions thrown (but not limited to):</b>
       
<p>
<tt><b><tt><b><a class="enumtype" href="t-pfcExceptions-XToolkitNotFound.html">IpfcXToolkitNotFound</a></b></tt></b></tt> - No font name is specified.</p>
</p>
<br>
<br>
</td>
</tr>
</table>
<br>
<hr>
<br>
<a name="Geometry">
<table cellpadding="5" cellspacing="0" border="0" class="method-def">
<tr>
<td class="return-type"><tt>Property</tt></td><td class="func-name"><tt>Geometry</tt></td><td class="return-type"><tt>as <a class="type" href="t-pfcGeometry-CurveDescriptor.html">IpfcCurveDescriptor</a></tt></td>
</tr>
</table>
</a>
<table border="0" class="method-doc">
<tr>
<td></td><td>
<br>The geometry of the detail entity.<br>
<br>When creating a "circle" detail entity, use an arc with a start
   angle of 0 and an end angle of 2*PI. Creo Parametric represents circle detail
   entities with the <tt><b><tt><b><a class="enumtype" href="t-pfcGeometry-ArcDescriptor.html">IpfcArcDescriptor</a></b></tt></b></tt> object.
   <br>
<br>
</td>
</tr>
</table>
<br>
<hr>
<br>
<a name="IsConstruction">
<table cellpadding="5" cellspacing="0" border="0" class="method-def">
<tr>
<td class="return-type"><tt>Property</tt></td><td class="func-name"><tt>IsConstruction</tt></td><td class="return-type"><tt>as Boolean [optional]</tt></td>
</tr>
</table>
</a>
<table border="0" class="method-doc">
<tr>
<td></td><td>
<br>Whether or not the entity is construction.  If <tt>null</tt>, the entity is not a construction entity.<br>
<br>
</td>
</tr>
</table>
<br>
<hr>
<br>
<a name="View">
<table cellpadding="5" cellspacing="0" border="0" class="method-def">
<tr>
<td class="return-type"><tt>Property</tt></td><td class="func-name"><tt>View</tt></td><td class="return-type"><tt>as <a class="type" href="t-pfcView2D-View2D.html">IpfcView2D</a> [optional]</tt></td>
</tr>
</table>
</a>
<table border="0" class="method-doc">
<tr>
<td></td><td>
<br>The drawing view associated with the entity.  This can be a view of a drawing model, or a drawing sheet background view.<br>
<br>
<p>
<b>Exceptions thrown (but not limited to):</b>
       
<p>
<tt><b><tt><b><a class="enumtype" href="t-pfcExceptions-XToolkitNotFound.html">IpfcXToolkitNotFound</a></b></tt></b></tt> - The entity is not attached to a drawing view.</p>
</p>
<br>
<br>
</td>
</tr>
</table>
<br>
<hr>
<br>
<a name="Width">
<table cellpadding="5" cellspacing="0" border="0" class="method-def">
<tr>
<td class="return-type"><tt>Property</tt></td><td class="func-name"><tt>Width</tt></td><td class="return-type"><tt>as Double [optional]</tt></td>
</tr>
</table>
</a>
<table border="0" class="method-doc">
<tr>
<td></td><td>
<br>The width of the entity line.  If <tt>null</tt>, the default width is used.<br>
<br>
</td>
</tr>
</table>
<br>
<br>
<hr>
<br>
<b>Method Detail</b>
<br>
<hr>
<br>
<a name="Create">
<table cellpadding="5" cellspacing="0" border="0" class="method-def">
<tr>
<td class="return-type"><tt>Function</tt></td><td class="func-name"><tt>CCpfcDetailEntityInstructions.Create</tt></td><td class="func-params"><tt>
 (inGeometry as <a class="type" href="t-pfcGeometry-CurveDescriptor.html">IpfcCurveDescriptor</a>, inView as <a class="type" href="t-pfcView2D-View2D.html">IpfcView2D</a> [optional])
 as <a class="type" href="t-pfcDetail-DetailEntityInstructions.html">IpfcDetailEntityInstructions</a></tt></td>
</tr>
</table>
</a>
<table border="0" class="method-doc">
<tr>
<td></td><td>
<br>Creates an instructions object describing how to construct a detail entity, for use in the methods <tt><b><a class="method" href="t-pfcDetail-DetailItemOwner.html#CreateDetailItem">IpfcDetailItemOwner.CreateDetailItem()</a></b></tt>, <tt><b><a class="method" href="t-pfcDetail-DetailSymbolDefItem.html#CreateDetailItem">IpfcDetailSymbolDefItem.CreateDetailItem()</a></b></tt> and <tt><b><a class="method" href="t-pfcDetail-DetailEntityItem.html#Modify">IpfcDetailEntityItem.Modify()</a></b></tt>.
<br>
<br>When creating a "circle" detail entity, use an arc with a start angle
   of 0 and an end angle of 2*PI. Creo Parametric represents circle detail entities
   with the <tt><b><tt><b><a class="enumtype" href="t-pfcGeometry-ArcDescriptor.html">IpfcArcDescriptor</a></b></tt></b></tt> object.<br>
<dl>
<dt>
<b>Parameters:</b>
</dt>
<dd>
<dl>
<dt>
<tt><b>inGeometry</b></tt>
</dt>
<dd>The curve geometry describing the trajectory of the detail entity (in screen coordinates).</dd>
<dt>
<tt><b>inView</b></tt>
</dt>
<dd>The drawing view associated with the entity.  This can be a model view obtained from <tt><b><a class="method" href="t-pfcModel2D-Model2D.html#List2DViews">IpfcModel2D.List2DViews()</a></b></tt>, or a drawing sheet background view obtained from <tt><b><a class="method" href="t-pfcSheet-SheetOwner.html#GetSheetBackgroundView">IpfcSheetOwner.GetSheetBackgroundView()</a></b></tt>.</dd>
</dl>
</dd>
</dl>
<dl>
<dt>
<b>Returns:</b>
</dt>
<dd>The created instructions object.</dd>
</dl>
</td>
</tr>
</table>
<br>
</body>
</html>
